# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrand', '0003_auto_20151216_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrandcompany',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, unique=True),
        ),
    ]
